### ISSUE TITLE
WIN release (msys2) asks for msys-2.0.dll

### ISSUE THREAD

**Issue by rwbc** [petur/seawall#1]
Hi Petur,

You should compile Seawall with the static flag or add your msys-2.0.dll version otherwise it won't run on most computers.
I tried the msys-2.0.dll (2022-05-13) from my msys2 installation, but this version doesn't work with it?

I have build my own msys2 compilation for my **old** hardware now,

**output from cmd**
```
uci
id name seawall 20220815
id author petur
option name Hash type spin default 1 min 1 max 65536
uciok
isready
readyok
position startpos
go depth 12
info depth 1 seldepth 1 score cp 40 nodes 20 time 0 nps inf pv g1f3
info depth 2 seldepth 2 score cp 15 nodes 81 time 0 nps inf pv g1f3 g8f6
info depth 3 seldepth 3 score cp 46 nodes 725 time 1 nps 725000 pv d2d4 g8f6 c1g5
info depth 4 seldepth 4 score cp 15 nodes 2504 time 2 nps 1252000 pv d2d4 d7d5 c1g5 c8g4
info depth 5 seldepth 6 score cp 40 nodes 6905 time 4 nps 1726250 pv d2d4 d7d5 g1f3 c8g4 c1g5
info depth 6 seldepth 7 score cp 15 nodes 25764 time 11 nps 2342182 pv d2d4 d7d5 g1f3 g8f6 c1g5 c8g4
info depth 7 seldepth 8 score cp 31 nodes 46585 time 20 nps 2329250 pv d2d4 d7d5 g1f3 g8f6 b1c3 c8g4 c1g5
info depth 8 seldepth 10 score cp 20 nodes 174221 time 67 nps 2600313 pv e2e4 b8c6 d2d4 d7d5 e4e5 h7h6 c1f4 c8f5
info depth 9 seldepth 12 score cp 36 nodes 611206 time 232 nps 2634509 pv e2e4 d7d6 b1c3 g8f6 d2d4 b8c6 f1e2 e7e5 g1f3
info depth 10 seldepth 13 score cp 29 nodes 1090830 time 419 nps 2603413 pv e2e4 d7d6 b1c3 g8f6 d2d4 b8c6 g1f3 c8g4 h2h3 g4f3
info depth 11 seldepth 15 score cp 27 nodes 5420337 time 2118 nps 2559177 pv g1f3 g8f6 d2d4 d7d5 c1f4 c8f5 b1d2 e7e6 e2e3 f8d6 f3e5
info depth 12 seldepth 15 score cp 27 nodes 11891533 time 4840 nps 2456928 pv d2d4 d7d5 c1f4 g8f6 g1f3 c8f5 e2e3 e7e6 f1d3 f8d6 d3f5 e6f5
bestmove d2d4
```

BTW is this your real name _Pétur Runólfsson_?
(saw your new account at talkchess)

I guess you are from Iceland then? (for filling in the info into my XB/UCI chronology)

It would be welcome if you add some info about Seawall to the github readme.

Guenther (RWBC)

**Comment by petur** [comment]
Hi Guenther,

Thanks for testing this!

> You should compile Seawall with the static flag or add your msys-2.0.dll version otherwise it won't run on most computers. I tried the msys-2.0.dll (2022-05-13) from my msys2 installation, but this version doesn't work with it?

I already had the `-static` flag, but that is apparently not enough. I did however switch to using the mingw64 version of gcc to build the windows binaries, which I think fixes the issue.

> BTW is this your real name _Pétur Runólfsson_? (saw your new account at talkchess)
> 
> I guess you are from Iceland then? (for filling in the info into my XB/UCI chronology)

Yes to both.

> It would be welcome if you add some info about Seawall to the github readme.

I added some - but I don't want to put too much in there since it's likely to get obsolete fast.

**Comment by rwbc** [comment]
Thanks for the infos, Petur!
I added Seawall to my XB/UCI chronology yesterday.
