### ISSUE TITLE
No way to contact you

### ISSUE THREAD

**Issue by GrahamCCRL** [petur/seawall#2]
94TH AMATEUR SERIES (Division 9)

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ICCF-Pre2022HQ.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
4 cycles 36 rounds
All engines 64-bit where available

The top engine will gain automatic promotion. Any other changes of division will be at my discretion and may not necessarily involve playoff matches.

Participants

Qapla 0.1.1 64-bit
Anka 0.6.3 64-bit
SoFCheck 0.9.1 64-bit
Popochin 4.3 64-bit
Queen 4.05 64-bit (new)
Fornax 3 64-bit
Seawall 20220818 64-bit (new)
AdaChess 3.9.0-dev 64-bit (new)
Clovis 1.4 64-bit (new)
Cinnamon 2.5 64-bit (new)

Games and standings will be available after every six rounds from the following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=14493

Web based link for live viewing (courtesy of Jay - Berserk author).
http://tlcv.net/16093

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16093

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by petur** [comment]
Thanks for the testing, you can reach me at _peturrun at gmail dot com_.
